### ISSUE TITLE
Zeros are Filtered Out From Emitted Metrics

### ISSUE THREAD

**Issue by ccceeefff** [mikaelvesavuori/mikrometric#1]
I have a simple metric block which emits 0 or 1 based on the number of failures detected, like so:

```
const m = MikroMetric.start({
    namespace: 'test',
    serviceName: 'test'
});
m.putMetric('Failure', 0, 'Count');
m.flush();
```

However, the emitted metric seems to be missing the actual property value for `Failure` in this case. As such, the 0 value itself does not propagate into CloudWatch metrics when the line is emitted.

```
{
  "_aws": {
    "Timestamp": 1706138670828,
    "CloudWatchMetrics": [
      {
        "Namespace": "test",
        "Dimensions": [
          [
            "service"
          ]
        ],
        "Metrics": [
          {
            "Name": "Failure",
            "Unit": "Count"
          }
        ]
      }
    ]
  },
  "id": "dba277e9-13e3-4e0e-8cd3-5012e9e04556",
  "service": "test",
  "timestamp": "2024-01-24T23:24:30.828Z",
  "timestampEpoch": "1706138670828"
}
```

I believe that is occurring because of the following metadata filtering block on L284. This might work if its updated to only filter against nulls or empty strings.

https://github.com/mikaelvesavuori/mikrometric/blob/dbf23af39a16bd79429972c6cdc19b1205750add/src/domain/entities/MikroMetric.ts#L279-L288

**Comment by mikaelvesavuori** [comment]
Hey @ccceeefff!

Sorry about the delay in responding. This should be fixed in https://github.com/mikaelvesavuori/mikrometric/releases/tag/v1.0.10.

**Comment by mikaelvesavuori** [comment]
I will close this as this should close the issue.

**Comment by ccceeefff** [comment]
Thanks for taking a look! Pretty nifty and easy to use library btw!
